spring:
  cloud:
    stream:
      bindings:
        output: # Maps to the source.output() channel in SimpleSourceBean
          destination: orgChangeTopic # Bind the service to Kafka with this topic name
          content-type: application/json
      kafka:
        binder:
          zkNodes: localhost # Network address of Zookeeper server running with Kafka
          brokers: localhost # Network address of the Kafka message brokers

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.stephensheldon: DEBUG